# The question text can be modified by the survey owner.
question: "说说你觉得plugin这个项目怎么样？(什么都行)"
# The instructions to the question can be modified by the survey owner. It's recommended that the existing instructions are included in the customised instructions.
instruction: ""
# For the purposes of reproducing a bug
options: [
        { "code": "1", "content": "看法" },
        # { "code": "2", "content": "短袖" },
        # { "code": "3", "content": "长裤" },
        # { "code": "4", "content": "运动鞋" },
        # { "code": "5", "content": "外套" },
        # { "code": "6", "content": "羽绒服" },
        # { "code": "7", "content": "毛衣" },
        # { "code": "8", "content": "苹果" },
        # { "code": "9", "content": "梨子" },
        # { "code": "10", "content": "芒果" },
        # { "code": "11", "content": "火龙果" },
        # { "code": "12", "content": "葡萄" },
        # { "code": "13", "content": "榴莲" },
        # { "code": "14", "content": "牛奶" },
        # { "code": "15", "content": "果汁" },
        # { "code": "16", "content": "啤酒" },
        # { "code": "17", "content": "白酒" },
        # { "code": "18", "content": "奶茶" },
        # { "code": "19", "content": "咖啡" },
        # { "code": "23", "content": "DVD" },
        # { "code": "24", "content": "VCD" },
        # { "code": "25", "content": "黑白电视机" },
        # { "code": "26", "content": "哑铃" },
        # { "code": "27", "content": "单杠" },
        # { "code": "28", "content": "洗衣机" },
        # { "code": "29", "content": "电磁炉" },
        # { "code": "30", "content": "薯片" },
        # { "code": "31", "content": "大众汽车" },
        # { "code": "32", "content": "雪佛兰汽车" },
        # { "code": "33", "content": "梅赛德斯奔驰" },
        # { "code": "34", "content": "打印机" },
        # { "code": "35", "content": "打印机配件" },
        # { "code": "36", "content": "修眉刀" },
        # { "code": "37", "content": "睫毛夹" },
    ]
